name: Build and deploy Python app to Azure Web App - FE-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'FE-AI'
  PYTHON_VERSION: '3.13'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies with compatibility fix
        run: |
          python -m pip install --upgrade pip
          # 创建临时修复的 requirements.txt
          if [ -f requirements.txt ]; then
            # 替换不兼容的版本
            sed 's/faiss-cpu==1.7.4/faiss-cpu>=1.10.0/g' requirements.txt > requirements_fixed.txt
            pip install -r requirements_fixed.txt
          else
            pip install Flask==2.3.3 PyPDF2==3.0.1 docx2txt==0.8 sentence-transformers==2.2.2
            pip install "faiss-cpu>=1.10.0"
            pip install requests==2.31.0 werkzeug==2.3.7 gunicorn==21.2.0 python-dotenv==1.0.0 numpy==1.24.3
          fi

      - name: Create deployment package
        run: |
          zip -r deployment.zip . -x '.git/*' '.github/*' 'venv/*' '__pycache__/*' '*.env' '.env/*' 'deployment.zip'

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Deploy to Azure Web App using Publish Profile
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FE-AI'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: deployment.zip