name: Build and deploy Python app to Azure Web App - FE-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create deployment files
        run: |
          # Create deployment script
          cat > deploy.sh << 'EOF'
          #!/bin/bash
          pip install -r requirements.txt
          EOF
          
          chmod +x deploy.sh

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: Clean up previous deployment files
        run: |
          rm -f .deployment
          rm -f deploy.cmd
          rm -rf .python_packages
      
      - name: Create startup command
        run: |
          echo "python -m gunicorn app:app -b 0.0.0.0:\$PORT --workers 2 --threads 4 --timeout 60" > startup.txt
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_643FD801DFBB43E4AC6CB59067ABDA62 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC189ED222754FAEAA376A8B92C674D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4911353947E4413DBDED940179484F62 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'FE-AI'
          slot-name: 'Production'
          package: .