name: Build and deploy Python app to Azure Web App - FE-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # 改为 3.11，Azure 对 3.13 支持可能不完善

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create startup command file
        run: |
          echo 'python -m gunicorn app:app -b 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 60' > startup.txt
          
      - name: Create deployment configuration
        run: |
          # 创建部署配置文件
          cat > .deployment << EOF
          [config]
          SCM_COMMAND_IDLE_TIMEOUT = 1800
          SCM_LOGSTREAM_TIMEOUT = 1800
          EOF

      - name: Clean up before packaging
        run: |
          # 移除不必要的文件
          rm -rf __pycache__
          rm -rf .git
          find . -name "*.pyc" -delete
          find . -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

      - name: Create deployment package
        run: |
          # 创建 ZIP 包（可选）
          zip -r deployment.zip . -x "*.git*" "*.github*" "*.vscode*" "__pycache__/*" "*.pyc"

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/
            !.git/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      
      - name: List files for debugging
        run: ls -la
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_643FD801DFBB43E4AC6CB59067ABDA62 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FC189ED222754FAEAA376A8B92C674D7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4911353947E4413DBDED940179484F62 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'FE-AI'
          slot-name: 'Production'
          package: .