name: Build and deploy Python app to Azure Web App - FE-AI

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: 'FE-AI'
  PYTHON_VERSION: '3.13'  # 改为 3.13 以匹配 Azure 配置

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Create deployment package
        run: |
          # 创建干净的部署包，排除不必要的文件
          zip -r deployment.zip . -x '.git/*' '.github/*' 'venv/*' '__pycache__/*' '*.env' '.env/*'

      - name: Upload deployment package
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: deployment.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_01D4569B93514237BD8F43AAD2B8895C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C62C76D058F14B8E81D1C63592A37731 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F30A9685366F4F398217F32978026DF9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: deployment.zip
          # 移除 slot-name 或使用正确的值